### PR TITLE
Replacing missmarple to sourceforge

### PR DESCRIPTION
**Pull request by elbashandy**

### CODE REVIEW

**Comment by burlen** [comment]
@elbashandy any update of status on this one?

**Comment by elbashandy** [comment]
@burlen Some changes to CMakeLists file were needed. Will get back to it asap.

Should we assign priorities in TECA_superbuild as well?

**Comment by elbashandy** [comment]
@burlen I suggest we merge this before implementing travis-ci workflow on the superbuild

**Comment by elbashandy** [comment]
@burlen I pushed my new changes here

supporting
- libffi
- pcre
- setuptools_scm
- six

I am still getting an error with SWIG not being able to find the pcre library. Also was fixed when I installed it using the package-manager.

**Pull request merged**
