### PR TITLE
Update superbuild packages

### LINKED ISSUE #30: pcre needed on ubuntu and sierra
Build failed at SWIG step due to missing pcre library.  Encountered this on ubuntu previously, and encountered now on MacOS Sierra.  `brew install pcre` fixed for Mac and `apt-get install libpcre3-dev` fixed for Ubuntu.

I'd suggest adding pcre to the superbuild, since it is not always readily available.

### PR DESCRIPTION
**Pull request by elbashandy**
resolves #30

### CODE REVIEW

**Comment by elbashandy** [comment]
@burlen can we merge this? I need these updates for the travis-ci integration as it includes the pcre package

**Comment by burlen** [comment]
I've made the changes to the repo to use the same git workflow that we've adopted in TECA. You can put your Python upgrades in now as well. Set `TECA_SOURCE=develop`.

**Comment by elbashandy** [comment]
Sounds good! Thanks

**Comment by elbashandy** [comment]
@burlen I had to add `wheel` as well for `kiwisolver`. This was only needed when I updated to Python 3.8.5. The new version of `kiwisolver` worked fine without `wheel` with Python 3.7

**Pull request merged**
